// =============================================================================
// contract-check.generated.ts
// =============================================================================
// GENERATED by `./builder shell:freeze` — do not edit by hand.
//
// Proves shell-ui's live api.ts surface still conforms to frozen ShellApiV0.
// A removed or narrowed member breaks this file under `tsc --noEmit`.
// =============================================================================

import type { ShellApiV0 } from 'shell-api/versions/v0';
import type { ShellApiShape } from './api';
import type { ShellAppProps as Frozen_ShellAppProps } from 'shell-api/versions/v0';
import type { ShellAppProps as Current_ShellAppProps } from './api';
import type { ShellSidebarProps as Frozen_ShellSidebarProps } from 'shell-api/versions/v0';
import type { ShellSidebarProps as Current_ShellSidebarProps } from './api';
import type { AppDescriptor as Frozen_AppDescriptor } from 'shell-api/versions/v0';
import type { AppDescriptor as Current_AppDescriptor } from './api';
import type { ShellApiConfig as Frozen_ShellApiConfig } from 'shell-api/versions/v0';
import type { ShellApiConfig as Current_ShellApiConfig } from './api';
import type { ShellConfig as Frozen_ShellConfig } from 'shell-api/versions/v0';
import type { ShellConfig as Current_ShellConfig } from './api';
import type { Editor as Frozen_Editor } from 'shell-api/versions/v0';
import type { Editor as Current_Editor } from './api';
import type { WorkspaceBinding as Frozen_WorkspaceBinding } from 'shell-api/versions/v0';
import type { WorkspaceBinding as Current_WorkspaceBinding } from './api';
import type { AppManifestEntry as Frozen_AppManifestEntry } from 'shell-api/versions/v0';
import type { AppManifestEntry as Current_AppManifestEntry } from './api';

// The live shell API shape must remain assignable to the frozen contract.
const _conformance: ShellApiV0 = {} as ShellApiShape;
void _conformance;

// Each individually-exported contract type must still be satisfied.
const _check_ShellAppProps: Frozen_ShellAppProps = {} as Current_ShellAppProps;
void _check_ShellAppProps;
const _check_ShellSidebarProps: Frozen_ShellSidebarProps = {} as Current_ShellSidebarProps;
void _check_ShellSidebarProps;
const _check_AppDescriptor: Frozen_AppDescriptor = {} as Current_AppDescriptor;
void _check_AppDescriptor;
const _check_ShellApiConfig: Frozen_ShellApiConfig = {} as Current_ShellApiConfig;
void _check_ShellApiConfig;
const _check_ShellConfig: Frozen_ShellConfig = {} as Current_ShellConfig;
void _check_ShellConfig;
const _check_Editor: Frozen_Editor = {} as Current_Editor;
void _check_Editor;
const _check_WorkspaceBinding: Frozen_WorkspaceBinding = {} as Current_WorkspaceBinding;
void _check_WorkspaceBinding;
const _check_AppManifestEntry: Frozen_AppManifestEntry = {} as Current_AppManifestEntry;
void _check_AppManifestEntry;
